feat: added skynet protocol
argoapp-live/argo-react pull request #152
Opened 2021-06-08 17:29 UTC by nitinshr135

1. Added select-protocol page to select between 'Arweave' and 'Skynet' protocols
    - Added cards for 'Arweave' and 'Skynet' (DeploySiteConfig)
    - Removed the continue button
    - Modified the continue and back buttons for navigating to the previous/next page

2. Added badge for the respective protocols for deployments in all deploys list (DeploymentItem)

3. Modified deployment page
    - Modified the protocol image, site preview link rendered while deploying (Deployment)
    - Modified the logs for their respective deployed protocols

4. Modified top card so that it shows respective protocol image and deployed link (ProjectTopCard)

2021-06-09 12:55 UTC, rekpero requested changes
LGTM! Just make sure when showing the protocol UI element, don't tightly couple it with one protocol, you can use a switch statement for this kind of situation.

2021-06-09 12:55 UTC, rekpero commented on src/components/DeploySiteConfig/DeploySiteConfig.tsx
> +  function clickArweave() {
don't need to put 2 diff function for this, you can do it in one function like this:
```
const selectProtocol = (protocol: string) => {
    setProtocol(protocol);
    setCreateDeployProgress(3);
}
```

And when you call this function, do it like:
`selectProtocol("arweave")`

2021-06-09 12:55 UTC, rekpero commented on src/components/DeploySiteConfig/DeploySiteConfig.tsx
> +                            onClick={(e) => clickArweave()}
Use what I said earlier in the comment
put `selectProtocol("arweave")` in place of this.

2021-06-09 12:55 UTC, rekpero commented on src/components/DeploySiteConfig/DeploySiteConfig.tsx
> +                            onClick={(e) => clickSkynet()}
Same thing here

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/AllDeployments/components/DeploymentItem/DeploymentItem.tsx
> +  const isArweave = deployment?.protocol === "arweave" ? true : false;
Make sure, you keep in mind that, this is not just one more protocol addition, we are going to support more than 2 protocols in the future. So if you do something like this, it's scalable in nature. Try to figure out how you can make it more flexible, so that in the future if you add another protocol, you can easily add it without changing the existing code.

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/AllDeployments/components/DeploymentItem/DeploymentItem.tsx
> +                {isArweave ? (
Not recommended, as it's not just Skynet and arweave, we will be adding more protocol

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/Deployment/Deployment.tsx
> +  const isArweave = currentSiteDeployConfig?.protocol === "arweave" ? true : false;
Same thing here, make sure it is not tightly coupled with any one protocol.

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/Deployment/Deployment.tsx
> +            {isArweave ? (
here too

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/_SharedComponent/ProjectTopCard/ProjectTopCard.tsx
> +  const isArweave = latestDeployment?.protocol === "arweave" ? true : false;
same thing

2021-06-09 12:55 UTC, rekpero commented on src/components/Sites/routes/_SharedComponent/ProjectTopCard/ProjectTopCard.tsx
> +            {isArweave ? (
same stuff

2021-06-14 08:32 UTC, nitinshr135 commented on src/components/DeploySiteConfig/DeploySiteConfig.tsx
> +  function clickArweave() {
added one function `selectProtocol` replacing two

2021-06-14 08:33 UTC, nitinshr135 commented on src/components/Sites/routes/AllDeployments/components/DeploymentItem/DeploymentItem.tsx
> +  const isArweave = deployment?.protocol === "arweave" ? true : false;
added switch statement for flexibility and scalability

2021-07-06 17:55 UTC, rekpero approved these changes

2021-07-06 17:55 UTC, merged