feature: archive
argoapp-live/argo-react pull request #196
Opened 2021-08-27 18:46 UTC by nitinshr135

- Added archive/unarchive div in Project-Settings
- Added archive project list in Organization-Settings
- Error handling in deploy-site-config
- Added error message in deploy-site-config
- Added archive-tag in project-top-card
- Big changes in project-top-card divs, optimized the div names and their CSS
- Added "state" in IProject

2021-09-11 13:10 UTC, rekpero requested changes
LGTM @nitinshr135 !!
Just some small update, please resolve them

2021-09-11 13:10 UTC, rekpero commented on src/components/Sites/routes/_SharedComponent/ProjectTopCard/ProjectTopCard.tsx
> +                      <></>
```suggestion
                      null
```
Put this if you don't have anything to show

2021-09-11 13:10 UTC, rekpero commented on src/components/Sites/routes/_SharedComponent/ProjectTopCard/ProjectTopCard.tsx
> +                    <></>
```suggestion
                    null
```
Same stuff

2021-09-11 13:10 UTC, rekpero commented on src/components/Dashboard/routes/Settings/Settings.tsx
>            {/* <div className="settings-bar-item">OAuth</div>
Remove these

2021-09-11 13:10 UTC, rekpero commented on src/components/Dashboard/routes/Settings/routes/SettingsArchive/SettingsArchive.scss
> +            // .protocol-tag-container {
Remove these if not required later

2021-09-11 18:39 UTC, nitinshr135 commented on src/components/Sites/routes/_SharedComponent/ProjectTopCard/ProjectTopCard.tsx
> +                    <></>
committed the requested changes

2021-09-13 14:17 UTC, rekpero approved these changes

2021-09-13 16:31 UTC, merged