adds confetti and share popup
argoapp-live/argo-react pull request #201
Opened 2021-09-11 13:29 UTC by nitinshr135

Adds 
- Confetti on successful payment
- Share button to share the deployment

2021-09-12 07:28 UTC, rekpero requested changes
LGTM! @nitinshr135 please resolve the comments

2021-09-12 07:28 UTC, rekpero commented on package.json
> +    "react-use": "^17.2.4",
Is this package anywhere used? If not remove it and run `npm install` or `yarn install`

2021-09-12 07:28 UTC, rekpero commented on package.json
> +    "canvas-confetti": "^1.4.0",
Is this also anywhere used? Otherwise remove it and run `npm install` or `yarn install`

2021-09-12 07:28 UTC, rekpero commented on package.json
> +    "@types/canvas-confetti": "^1.4.2",
same with this as well

2021-09-12 07:28 UTC, rekpero commented on package.json
> +    "@types/canvas-confetti": "^1.4.2",
@nitinshr135 make sure you clean up any packages before commit if they are not getting used anywhere

2021-09-12 07:28 UTC, rekpero commented on src/components/Sites/routes/Deployment/Deployment.tsx
> +                  <div className="modal-container">
Please create a different component for this modal and replace this code with a component and pass any data thru props.

2021-09-13 11:26 UTC, nitinshr135 commented on src/components/Sites/routes/Deployment/Deployment.tsx
> +                  <div className="modal-container">
added different component for modal, cleaned code

2021-09-13 11:57 UTC, rekpero approved these changes
LGTM!!

2021-09-13 16:32 UTC, merged