invite member
argoapp-live/argo-react pull request #202
Opened 2021-09-11 13:53 UTC by nitinshr135

Adds
- Invited Members tab in Members 
- Success or failure popup for invite mail
- error message in inviteCallback

2021-09-12 07:31 UTC, rekpero requested changes
LGTM!! @nitinshr135 please clean up the code before raising a PR

2021-09-12 07:31 UTC, rekpero commented on src/components/Dashboard/routes/InviteMembers/InviteMembers.tsx
> +  // const emailChecker = () => {
Remove this if not used

2021-09-12 07:31 UTC, rekpero commented on src/components/Dashboard/routes/InviteMembers/InviteMembers.tsx
> +                {!inviteMemberLoading ? (
Put this in a diff component and pass it here

2021-09-12 07:31 UTC, rekpero commented on src/components/Dashboard/routes/Members/Members.tsx
> +  // const [memberDeleted, setMemberDeleted] = useState<boolean>();
remove this

2021-09-12 07:31 UTC, rekpero commented on src/components/Dashboard/routes/Members/Members.tsx
> +  // useEffect(() => {
Remove this

2021-09-12 07:31 UTC, rekpero commented on src/services/ApiService.ts
> +// export const getInviteList = (organizationId: string): Observable<any> => {
remove this

2021-09-13 11:56 UTC, rekpero requested changes
@nitinshr135 fix this asap. everything else looks good to go

2021-09-13 11:56 UTC, rekpero commented on src/components/InvitePopup/InvitePopup.tsx
> +import React, { useContext } from "react";
Put this component in the InviteMember component as it is connected to only that.

2021-09-13 12:16 UTC, nitinshr135 commented on src/components/InvitePopup/InvitePopup.tsx
> +import React, { useContext } from "react";
yes, changes made

2021-09-13 12:37 UTC, rekpero approved these changes
LGTM

2021-09-13 16:32 UTC, merged